/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox;

import java.io.IOException;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void run_mt() throws IOException {
        App.main(new String[] {"build/resources/test/mt.lox"});
    }

    @Test void run_var() throws IOException {
        App.main(new String[] {"build/resources/test/var.lox"});
    }

    @Test void run_cond() throws IOException {
        App.main(new String[] {"build/resources/test/cond.lox"});
    }

    @Test void run_loop() throws IOException {
        App.main(new String[] {"build/resources/test/loop.lox"});
    }

}
