/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox;

import java.io.IOException;

public class App {
    private static Lox instance;

    private static Lox getInstance() {
        if (instance == null) {
            instance = new Lox();
        }

        return instance;
    }

    public static void main(String[] args) throws IOException {
        getInstance().run(args);
    }

    public static void error(int line, String msg) {
        getInstance().error(line, msg);
    }
}
